/* Generated by Interface Builder */

#pragma once

#import "Anchor.h"
#import "HyperAccess.h"
#import <Foundation/Foundation.h>

@interface TextToy : NSObject {
    id SearchWindow;

    Anchor *StartAnchor;
    Anchor *EndAnchor;

    NSMutableArray *accesses;
}

- setSearchWindow:anObject;

#ifdef JUNK
- Do_getStartLength:sender;
- Do_getSel:sender;
- Do_setBackgroundGray:sender;
#endif

/*	Link handling:
*/
- (IBAction)linkToMark:sender;
- (IBAction)linkToNew:sender;
- (IBAction)unlink:sender;
- (IBAction)markSelected:sender;
- (IBAction)markAll:sender;
- (IBAction)followLink:sender;
- (IBAction)dump:sender;

//	Access manager function:

- (void)registerAccess:(HyperAccess *)access;

@end
