
/* Generated by Interface Builder */

#import <AppKit/AppKit.h>

@interface StyleToy:NSObject
{
    NSForm	*TabForm;
    NSForm	*ParameterForm;
    NSWindow *StylePanel;
    NSForm	*NameForm;
}

+new;

- loadDefaultStyleSheet;
- setTabForm:(NSForm *)anObject;
- setParameterForm:(NSForm *)anObject;
- setStylePanel:(NSWindow *)anObject;
- setNameForm:(NSForm *)anObject;
- NextButton:sender;
- FindUnstyledButton:sender;
- ApplyButton:sender;
- heading1Button:sender;
- heading2Button:sender;
- heading3Button:sender;
- heading4Button:sender;
- heading5Button:sender;
- heading6Button:sender;
- normalButton:sender;
- addressButton:sender;
- exampleButton:sender;
- listButton:sender;
- glossaryButton:sender;
- PreviousButton:sender;
- SetButton:sender;
- PickButton:sender;
- ApplyToSimilar:sender;
- open:sender;
- saveAs:sender;
@end
