
/* Generated by Interface Builder */

#import <AppKit/AppKit.h>

@interface StyleToy : NSObject {
}

@property(nonatomic) NSWindow *StylePanel;
@property(nonatomic) IBOutlet NSForm *TabForm;
@property(nonatomic) IBOutlet NSForm *ParameterForm;
@property(nonatomic) IBOutlet NSForm *NameForm;

- init;

- (void)loadDefaultStyleSheet;
- (IBAction)NextButton:sender;
- (IBAction)FindUnstyledButton:sender;
- (IBAction)ApplyButton:sender;
- (IBAction)heading1Button:sender;
- (IBAction)heading2Button:sender;
- (IBAction)heading3Button:sender;
- (IBAction)heading4Button:sender;
- (IBAction)heading5Button:sender;
- (IBAction)heading6Button:sender;
- (IBAction)normalButton:sender;
- (IBAction)addressButton:sender;
- (IBAction)exampleButton:sender;
- (IBAction)listButton:sender;
- (IBAction)glossaryButton:sender;
- (IBAction)PreviousButton:sender;
- (IBAction)SetButton:sender;
- (IBAction)PickButton:sender;
- (IBAction)ApplyToSimilar:sender;
- (IBAction)open:sender;
- (IBAction)saveAs:sender;
@end
