/* Generated by Interface Builder */

#pragma once

#import "HyperAccess.h"
#import "HyperManager.h"

@interface TcpAccess : HyperAccess {
}

@property(nonatomic) IBOutlet HyperManager *manager;

@end
