#!/bin/bash

set -e
cd "$(dirname $0)/.."

# TODO: We should move this to a Makefile or ideally a custom Xcode build rule

Scripts/convert-nib-to-xib \
    Legacy/WorldWideWeb.app/WorldWideWeb.nib \
    -o WorldWideWeb/UI/WorldWideWeb.xib
